name: architector
channels:
  - conda-forge
dependencies:
  - python
  - xtb-python
  - crest
  - ase
  - numpy
  - py3Dmol
  - openbabel
  - scipy
  - jupyter
  - numba
  - pandas
  - crest
  - pynauty
  - tqdm
  - mendeleev
  - tblite
  - tblite-python
