name: testing
channels:
  - conda-forge
dependencies:
  - python
  - xtb>6.5
  - ase
  - numpy
  - openbabel
  - scipy
  - numba
  - py3Dmol
  - pandas
  - crest
  - pynauty
  - tqdm
  - mendeleev
  - tblite-python