# This workflow is used to test, if the installation of the pypi package works

name: Pip check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: cp .ci_support/environment.yml environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: '3.10'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        use-mamba: true
    - name: Update environment
      shell: bash -l {0}
      run: mamba env update -n my-env -f environment.yml
    - name: Pip check
      shell: bash -l {0}
      run: |
        pip install --no-deps .
        pip check
