name: Tests

on:
  push:
    branches: [main, Secondary_Solvation_Shell]
  pull_request:
    branches: [main, Secondary_Solvation_Shell]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: 'latest'
          environment-name: test-env
          create-args: >-
            python=3.12
            ase
            numpy
            openbabel
            scipy
            numba
            py3Dmol
            pandas
            crest
            xtb>6.5
            pynauty
            tqdm
            mendeleev
            tblite-python
          init-shell: bash

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install package
        run: |
          uv pip install --no-deps -e .

      - name: Run tests
        run: |
          python -m unittest discover tests
